name: Architect of Light
favicon: null
layout_spectrum: 0.48706
typography_spectrum: 0.23143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#343331'
    - '#4f4e4c'
    - '#a09f9b'
    - '#bfbbb8'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
