name: Architect of Light
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#b5b4b0'
    - '#5c665a'
    - '#1f1f1f'
    - '#00486c'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
