name: Architect of Light
favicon: null
layout_spectrum: 0.83786
typography_spectrum: 0.23143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff4c00'
    - '#ffff30'
    - '#692f06'
    - '#ffba22'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
