name: Architect of Light
favicon: null
layout_spectrum: 0.74594
typography_spectrum: 0.23143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1912'
    - '#e4e5df'
    - '#665547'
    - '#0071a9'
    - '#6bb0d5'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
